version: "3"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001

  strapi:
    container_name: strapi
    platform: linux/x86_64
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: strapi
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    build:
      context: ./strapi
      dockerfile: ./Dockerfile
    volumes:
      - ./strapi:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - 5432:5432
